# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addEventSucessfully(self):
    self.driver.get("https://sandbox.moodledemo.net/my/courses.php/my/")
    self.driver.set_window_size(520, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".float-sm-right").click()
    self.driver.execute_script("window.scrollTo(0,279.20001220703125)")
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Hellow")
    self.driver.find_element(By.ID, "yui_3_18_1_1_1701754997233_332").click()
    self.driver.execute_script("window.scrollTo(0,300)")
  
  def test_addEventAlternative(self):
    self.driver.get("https://sandbox.moodledemo.net/my/")
    self.driver.set_window_size(520, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".float-sm-right").click()
    self.driver.execute_script("window.scrollTo(0,378.3999938964844)")
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Dinh Sô")
    self.driver.find_element(By.ID, "id_eventtype").click()
    dropdown = self.driver.find_element(By.ID, "id_eventtype")
    dropdown.find_element(By.XPATH, "//option[. = 'Course']").click()
    self.driver.find_element(By.ID, "form_autocomplete_input-1701755950000").click()
    self.driver.find_element(By.CSS_SELECTOR, "#form_autocomplete_suggestions-1701755950000 > li:nth-child(2)").click()
    self.driver.find_element(By.ID, "yui_3_18_1_1_1701755910785_350").click()
  
  def test_failEventNameError(self):
    self.driver.get("https://sandbox.moodledemo.net/my/")
    self.driver.set_window_size(520, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".float-sm-right").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".float-sm-right")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "yui_3_18_1_1_1701755459187_320").click()
    self.driver.find_element(By.ID, "id_error_name").click()
  
